on:
  pull_request:
    types:
      - opened
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: "setup node"
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: "test backend"
        run: |
          cd backend
          touch .env
          echo DB_URL=${{ secrets.DB_URL }} >> .env
          echo TEST_PW=${{ secrets.TEST_PW }} >> .en
          npm i
          npm test
